tap "agentwrapper/tap"
tap "theboredteam/boring-notch", "https://github.com/TheBoredTeam/homebrew-boring-notch", trusted: { casks: ["boring-notch"] }
tap "vishvavariya/notchy"
brew "azure-cli"
brew "bash"
brew "bats-core"
brew "coreutils"
brew "dotnet@8", link: true
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gitleaks"
brew "herdr"
brew "lazygit"
brew "tree-sitter"
brew "neovim"
brew "node@22", link: true
brew "nvm"
brew "ripgrep"
brew "rust-analyzer"
brew "shellcheck"
brew "swiftlint"
cask "agentwrapper/tap/agent-orchestrator", trusted: true
cask "cmux"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "vishvavariya/notchy/notchy", trusted: true
